FROM pytorch/pytorch:2.4.0-cuda12.1-cudnn9-runtime

RUN pip install --no-cache-dir \
    torchvision==0.19.0 \
    numpy==1.26.4 \
    requests \
    pillow
RUN mkdir -p /root/.cache/torch/hub/checkpoints
RUN python3 -c "\
import torchvision.models as models; \
models.resnet152(weights=models.ResNet152_Weights.DEFAULT)"
WORKDIR /app
COPY resnet.py .
COPY image/ ./image/
