FROM nvidia/cuda:12.9.0-base-ubuntu22.04

# 1) Install system tools, build essentials and CUDA toolkit, plus Python3/venv/pip
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
      build-essential \
      nvidia-cuda-toolkit && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /workspace

COPY test4.cu .
COPY input_files/ input_files/
RUN   nvcc -o test4 test4.cu -lcudart
ENTRYPOINT ["./test4", "100", "100", "input_files/sequence.csv"]


