FROM nvidia/cuda:12.9.0-devel-ubuntu22.04

# 1) Install system tools, build essentials and CUDA toolkit, plus Python3/venv/pip
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
      build-essential && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /workspace

COPY test_sum.cu .
COPY test_sfu.cu .
COPY test_shared.cu .
COPY test_gemv.cu .
COPY test_fmul.cu .

COPY input_files/ input_files/

RUN   nvcc -o test_sum test_sum.cu -lcudart
RUN   nvcc -o test_sfu test_sfu.cu -lcudart
RUN   nvcc -o test_shard test_shard.cu -lcudart
RUN   nvcc -o test_gemv test_gemv.cu -lcudart
RUN   nvcc -o test_fmul test_fmul.cu -lcudart
